- app/components/About/components/Section/components/SectionAbout/components/MDX/about.mdx
Was missing closing parens for the hyperlink to the UCSC genome browser.
> Fix UCSC hyperlink markdown in about.mdx

- app/components/Roadmap/components/Section/components/SectionRoadmap/sectionRoadmap.tsx
This might have been intended as 'dataset' I guess but we don't use that term elsewhere here and data harmonization is clear and standard wording.
> fix roadmap typo - daset -> data. 

- app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.styles.ts
- app/components/Home/components/Section/components/SectionHelp/sectionHelp.styles.ts
- app/components/Home/components/Section/components/SectionHelp/sectionHelp.tsx
> feat: the return of "your questions answered!" (#56)

- app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.styles.ts
- app/components/Home/components/Section/components/SectionHelp/sectionHelp.styles.ts
- app/components/Home/components/Section/section.styles.ts
- app/components/Home/content/sectionSubHero.mdx
- pages/index.tsx
> feat: brc analytics home page hero link text (#85)

- app/components/content/sectionAbout.mdx
> fix: add space between fig caption on about page for mobile viewport (#119)

- app/components/Home/components/Section/components/SectionHero/components/Carousel/cards/constants.ts
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/index.tsx
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/webinar20241004.mdx
> feat: add carousel card for webinar video (#127)

- app/components/Layout/components/Detail/components/Section/section.styles.ts
- app/components/common/CopyText/copyText.tsx
- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
> feat: add copy to clipboard button next to dbKey (#121)

- app/components/Home/components/Section/components/SectionHero/components/Carousel/cards/constants.ts
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/index.tsx
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/webinar20241030.mdx
~~Note: the card text seems to be just long enough to get awkwardly low down on the card (not enough to overflow though)~~
Changing "We will" to "We'll" seems to make it fit better
> feat: add carousel card for 2024-10-30 webinar (#141)

- scripts/set-version.sh
> fix: append newline before other content in `set-version.sh` (#184)

- app/components/index.ts
- site-config/brc-analytics/local/config.ts
- site-config/brc-analytics/local/socialMedia.ts
- Added [Discourse](https://help.brc-analytics.org/) link to the site header and footer with the appropriate icon
- Resolved issue where navlinks opened in the same tab
> feat: added discourse header/footer button (#88)

- app/components/Table/components/TableCell/components/AnalyzeGenome/analyzeGenome.tsx
- package-lock.json
- package.json
- pages/_app.tsx
- site-config/brc-analytics/local/index/genomeEntityConfig.ts
> chore: upgrade findable and allow toggling all columns (#203, #204)

- app/components/Entity/components/AnalysisMethod/analysisMethod.styles.ts
- app/components/Entity/components/AnalysisMethod/analysisMethod.tsx
- app/components/Entity/components/AnalysisMethod/components/Workflow/constants.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/types.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.styles.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
- app/components/Entity/components/AnalysisMethod/constants.ts
- app/components/Entity/components/AnalysisMethod/types.ts
- app/components/Entity/components/AnalysisMethods/analysisMethods.styles.ts
- app/components/Entity/components/AnalysisMethods/analysisMethods.tsx
- app/components/Entity/components/AnalysisMethods/constants.ts
- app/components/Entity/components/AnalysisMethodsCatalog/analysisMethodsCatalog.tsx
- app/components/Home/components/Section/components/SectionHero/components/Hero/hero.tsx
- app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.tsx
- app/components/Layout/components/Hero/common/entities.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
Closes #279.
Analysis methods supports multiple workflows as per [mocks](https://www.figma.com/design/wxBBIrZcZb6IhYSg4d8B7J/BRC-Analytics-Homepage?node-id=1107-1109&m=dev).
Includes minor change to workflow hero (breadcrumbs and sub title).
> feat: support multiple analysis methods per category (#279)

- app/components/Entity/components/AnalysisMethod/analysisMethod.styles.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/constants.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.styles.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
Closes #300.
- Updates workflow card with "Launch Galaxy" button as per [mocks](https://www.figma.com/design/wxBBIrZcZb6IhYSg4d8B7J/BRC-Analytics-Homepage?node-id=1107-1109&m=dev).
> feat: update workflow card for "Launch Galaxy" button (#300)

- catalog/output/workflows.json
- catalog/source/workflows.yml
changed strategy a bit to try to go around the issue where some workflows may need support for additional pre-populated parameters, but still get some fun things on the site quickly.
this should get single read options for rnaseq and chipseq, add cutandrun, atacseq and some scrnaseq stuff.
also improved display names of some things. perhaps we want to improve those in iwc in future, and if so, probably an issue or two need filed somewhere for that?
feedback welcome
> feat: added additional workflows (#322)

- app/utils/galaxy-api.ts
> fix: use correct variant calling landing body even when gene model url is absent (#347)

- .prettierignore
Pulled off of #372 to have unrelated commits not grouped (when squashed).
Closes https://github.com/galaxyproject/brc-analytics/issues/373
> chore: add .venv to prettier ignore list (#373)

- .husky/commit-msg
This closes #363.  It drops the issue number check, but leaves the commitlint validation.  If we want to follow up with a github workflow enforcing that PRs reference an issue, that's fine.
Also adds .venv to prettierignore.
> chore: Remove issue number check from husky (#363)

- .github/actions/check-input-commit-message/action.yml
- .github/actions/check-input-commit-message/index.js
- .github/workflows/check-pr-title.yml
- package-lock.json
- package.json
Closes #377
[GitHub's documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks) recommends using a JavaScript action over using scripts in a YAML workflow when working with things like a PR title, so I've created a custom action to do the checks
See examples of [failing issue number](https://github.com/galaxyproject/brc-analytics/actions/runs/13807201667/job/38620406711#step:6:12), [failing Conventional Commits](https://github.com/galaxyproject/brc-analytics/actions/runs/13807395845/job/38620984585#step:6:16), and [failing both](https://github.com/galaxyproject/brc-analytics/actions/runs/13807174049/job/38620322910#step:6:16) (note: these were before the …
> ci: add github action and workflow to check pr title for commit message format (#377)

- app/apis/catalog/brc-analytics-catalog/common/entities.ts
- app/components/Entity/components/AnalysisMethodsCatalog/analysisMethodsCatalog.tsx
- catalog/build/py/generated_schema/schema.py
- catalog/build/ts/build-catalog.ts
- catalog/output/workflows.json
- catalog/schema/generated/schema.ts
- catalog/schema/generated/workflow_categories.json
- catalog/schema/workflow_categories.yaml
- catalog/source/workflow_categories.yml
resolves #442 
sets 'assembly' and 'consensus sequence' to not show as coming soon when an assembly doesnt have a compatible workflow
open to better names for the new 'show_coming_soon' if someone has one
> feat: optionally hide 'coming soon' for empty workflow categories (#442)

- .eslintrc.json
- app/utils/galaxy-api.ts
- catalog/build/py/generated_schema/schema.py
- catalog/schema/enums/workflow_parameter_variable.yaml
- catalog/schema/generated/schema.ts
- catalog/schema/generated/workflows.json
Very minimal (just adding a new value to the enum and a placeholder case to the switch statement), but I think this is all that's useful to do unless we have a specific plan for what the relevant input and output to `paramVariableToRequestValue` needs to look like
Hopefully I spelled "Sanger" correctly -- I think it's misspelled in the ticket
> feat: add stub of SANGER_READ_RUN workflow parameter variable (#459)

- catalog/build/py/generated_schema/schema.py
- catalog/schema/enums/outbreak_priority.yaml
- catalog/schema/enums/outbreak_resource_type.yaml
- catalog/schema/generated/outbreaks.json
- catalog/schema/generated/schema.ts
- catalog/schema/outbreaks.yaml
- catalog/schema/schema.yaml
- catalog/schema/scripts/source-file-schema-names.sh
- catalog/source/outbreaks.yml
- catalog/source/outbreaks/aspergillus.md
- catalog/source/outbreaks/avian_influenza.md
- catalog/source/outbreaks/candida_auris.md
- catalog/source/outbreaks/coccidioides_posadasii.md
- catalog/source/outbreaks/covid19.md
- catalog/source/outbreaks/cryptococcus_neoformans.md
- catalog/source/outbreaks/cryptosporidium_parvum.md
- catalog/source/outbreaks/histoplasma_capsulatum.md
- catalog/source/outbreaks/leishmania.md
- catalog/source/outbreaks/malaria.md
- catalog/source/outbreaks/mpox.md
- catalog/source/outbreaks/mucorales.md
- catalog/source/outbreaks/naegleria_fowleri.md
- catalog/source/outbreaks/plasmodium_falciparum.md
- catalog/source/outbreaks/tuberculosis.md
resolves #450
supersedes #242, but lifts information from it
based on the list and info from #353 
makes some hopefully well-informed assumptions:
1. that for organism groups like the mucorales fungi, we want a single entry under outbreaks that can highlight specific descendants
2. we may want to stop showing certain entries without having to remove them, as the status of things change
3. we may want to display different types of resources about an outbreak slightly differently
4. we can figure out a way to meaningfully associate arbitrary taxonomic ranks (ex: 38574) with their descendant organisms and assemblies (outside of just the highlighted ones) if we would like
5. when the taxonomy id associated w an outbreak is actually mapped to an organism specifically (rather than a group of …
> feat: add outbreak schema and initial outbreaks (#450)

- .husky/pre-commit
- catalog/build/py/build-files-from-ncbi.py
- catalog/build/py/generated_schema/schema.py
- catalog/build/py/iwc_manifest_to_workflows_yaml.py
- catalog/build/py/package/catalog_build/build.py
- catalog/build/py/package/setup.py
- catalog/build/py/requirements.txt
- catalog/schema/scripts/gen-typescript.py
- package.json
- pyproject.toml
- scripts/format-python.sh
Just like we use prettier for js, this applies `ruff` for python.  We use black-style formatting, and sort imports a-la isort.
Closes #393.
Also, please leave this in draft until the data portion of the genome-viz stuff (#290) is merged to avoid extra conflict resolution work.  I'll reapply black here once that's in.
> style:  apply consistent python formatting, import sorting --  automate w/ ruff #393

- app/apis/catalog/brc-analytics-catalog/common/entities.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/hooks/UseLaunchGalaxy/useLaunchGalaxy.ts
- app/utils/galaxy-api/entities.ts
- app/utils/galaxy-api/galaxy-api.ts
Closes #468
Based on `main` as opposed to (as suggested in the ticket) `fran/456-paired-end-step` because the latter has linting errors which would make things awkward
> feat: return collection for `SANGER_READ_RUN` workflow parameter variable (#468)

- app/components/Home/components/Section/components/SectionViz/sunburst.tsx
Adjusts the visual arc stroke on hover to more clearly indicate the highlighted option.
Filters on-arc display to only show when there is sufficient size (an estimate, but tweakable and better than nothing).
Swaps tooltip background to a theme color which looks a lot better.
Screenshots
Before:
After:
> feat: visibility and navigation improvements for hierarchical viz (#289)

- app/components/Home/components/Section/components/SectionViz/NodeDetails.tsx
- app/components/Home/components/Section/components/SectionViz/sunburst.tsx
This pull request simplifies the user interface in the `SectionViz` component by removing redundant information and streamlining the display text for better readability. The most important changes are:
* [`NodeDetails.tsx`](diffhunk://#diff-2e793d58df5d8af3f0190b86a6d41864fa1d86510b38a3cab72bc60f344ceb98L124-R124): Simplified the filter link text by removing the dynamic assembly count and suffix, replacing it with a static message: "View assemblies for {nodeName}". This makes the text more concise and easier to understand.
* [`sunburst.tsx`](diffhunk://#diff-6c361bc88cd5bffde4a68a0f78ab95386a9c2f60002d1007728c1c856cf89cd2L208-R208): Updated the tooltip content to exclude the assembly count, leaving only the node name (`<strong>${d.data.name}</strong>`). This reduces clutter and focuses on …
> fix: remove count from sunburst tooltip/link for clarity #481 #545 #522

- .github/actions/check-input-commit-message/index.js
- .github/pull_request_template.md
Removes the mandatory #xxx issue reference requirement from PR titles while adding a PR template that encourages linking to existing issues when relevant.
One option to close #586; draft pending discussion.
> chore: remove required GitHub issue linking from PR title validation

- app/components/Home/components/Section/components/SectionHero/components/Hero/hero.tsx
- app/components/Home/components/Section/components/SectionViz/sunburst.tsx
- app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.tsx
This fixes the sunburst in safari. 
Three separate changes address different Safari-specific issues:
- The SVG width specification fix prevents Safari warnings
- The foreignObject replacement fixes Safari's known compatibility issues with HTML content in SVG
- The explicit dimensions fix ensures Safari can properly size the SVG within the flex container
Closes #590
> fix: sunburst display issues in firefox

- @types/theme.d.ts
- app/apis/catalog/brc-analytics-catalog/common/entities.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/AccessionSelector/accessionSelector.tsx
- app/styles/common/constants/palette.ts
- app/styles/common/mui/chip.ts
- app/theme/common/components.ts
- app/theme/common/palette.ts
- app/theme/theme.ts
- app/views/PriorityPathogenView/components/PriorityPathogens/priorityPathogens.styles.ts
- app/views/PriorityPathogenView/components/PriorityPathogens/priorityPathogens.tsx
- app/views/PriorityPathogenView/components/PriorityPathogens/types.ts
- app/views/PriorityPathogenView/components/PriorityPathogens/utils.ts
- app/views/PriorityPathogenView/priorityPathogensView.tsx
- app/views/PriorityPathogenView/types.ts
- app/views/PriorityPathogenView/utils.ts
- pages/_app.tsx
- pages/data/[entityListType]/index.tsx
- routes/constants.ts
- site-config/brc-analytics/local/config.ts
- site-config/brc-analytics/local/index/priorityPathogensEntityConfig.ts
Closes #506.
This pull request introduces a new "Priority Pathogens" feature, adds support for custom theming with new palette options, and updates navigation and routing to accommodate the new feature. The most significant changes include adding the "Priority Pathogens" view and related components, extending the theme with caution-related colors, and updating the app's navigation and routing logic.
* Added a `PriorityPathogensView` component to display priority pathogens data, including a styled grid layout, custom chips for priority levels, and a description section using `MDXRemote` for rendering. (`[[1]](diffhunk://#diff-dbbf351b6711744330990380fe4139a5af973b1cfefd6a773fc3e5f83ed36717R1-R45)`, `[[2]](diffhunk://#diff-ee4772085a389e9bb7a7bec09bc8b34d22f2e8086897ba90d67f29caa503fedfR1-R2 …
> feat: implement outbreaks page (#506)

- app/views/PriorityPathogensView/components/PriorityPathogens/priorityPathogens.styles.ts
- app/views/PriorityPathogensView/components/PriorityPathogens/priorityPathogens.tsx
- app/views/PriorityPathogensView/priorityPathogensView.styles.ts
- app/views/PriorityPathogensView/priorityPathogensView.tsx
Closes #610.
This pull request refactors the `PriorityPathogensView` component to improve responsiveness and update the styling for better alignment with design guidelines. Key changes include introducing responsive grid layouts, replacing `RoundedPaper` with `FluidPaper`, and customizing the `Index` component for consistent styling.
* Updated `StyledGrid` in `priorityPathogens.styles.ts` to use a single-column layout by default and switch to a two-column layout on tablet-sized screens or larger using the `mediaTabletUp` mixin.
* Added a styled `Index` component in `priorityPathogensView.styles.ts` to centralize layout adjustments, including responsive margins and maximum width for larger screens.
* Replaced `RoundedPaper` with `FluidPaper` in `PriorityPathogens` for a more modern and …
> feat: add responsive view to priority pathogens view (#610)

- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- site-config/brc-analytics/local/index/common/category/categories.ts
- site-config/brc-analytics/local/index/common/category/categoryRegistry.ts
- site-config/brc-analytics/local/index/common/category/configs.ts
- site-config/brc-analytics/local/index/common/category/mapSelectCategoryValue.ts
- site-config/brc-analytics/local/index/common/category/typeGuards.ts
- site-config/brc-analytics/local/index/common/category/utils.ts
- site-config/brc-analytics/local/index/common/column/columnDefs.ts
- site-config/brc-analytics/local/index/common/column/columnRegistry.ts
- site-config/brc-analytics/local/index/genomeEntityConfig.ts
- site-config/brc-analytics/local/index/organismEntityConfig.ts
Closes #609.
This pull request introduces functionality to support the display and management of "Priority" and "Priority Pathogen" data in the BRC Analytics Catalog. The changes include new utility functions, configurations for categories and columns, and updates to entity configurations to integrate these new features.
* Added `mapSelectCategoryValue` function to format select category values with a custom label formatter (`site-config/brc-analytics/local/index/common/category/mapSelectCategoryValue.ts`).
* Introduced `isOutbreakPriority` type guard to validate "Outbreak Priority" values (`site-config/brc-analytics/local/index/common/category/typeGuards.ts`).
* Created utility functions `mapPriority` and `mapPriorityPathogenName` to handle priority labels and pathogen names …
> feat: filter organism and assemblies by priority and priority group (#609)

- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
Closes #508.
This pull request adds a new key-value pair to the `buildAssemblyDetails` function, enhancing the assembly details with information about "Priority Pathogen."
* Added a new key-value pair `"Priority Pathogen"` to the `keyValuePairs` map, using the `buildPriorityPathogen` function to generate its value. This provides additional context for assemblies. (`[app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.tsR147-R150](diffhunk://#diff-c7a9aefa9288341532869ba9987b67c489fce1e3b9e10c08643d92d54691ee11R147-R150)`)
> feat: add outbreak tag to workflow (#508)

- app/views/PriorityPathogensView/constants.ts
This pull request updates the priority mapping in the `PRIORITY` constant to reflect a revised priority ranking system.
Changes to priority mapping:
* [`app/views/PriorityPathogensView/constants.ts`](diffhunk://#diff-71c1244d4f495efc7700806d641aa8e01bc75867d23f846a3e145e783781f0c8L4-R6): Adjusted the numeric values for `CRITICAL` (from 1 to 2) and `HIGHEST` (from 2 to 1) to reflect their updated priority levels.
> feat: re-order priority to make highest first (#625)

- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
Closes #630.
This pull request introduces a new functionality to improve user interaction with priority pathogen details in the BRC Analytics Catalog. Specifically, it adds a click handler to the priority pathogen chip, allowing users to navigate to a filtered view of organisms based on the priority pathogen's category and value.
* [`app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts`](diffhunk://#diff-c7a9aefa9288341532869ba9987b67c489fce1e3b9e10c08643d92d54691ee11R431-R443): Added an `onClick` handler to the `Chip` component in `buildPriorityPathogenDetails`. The handler uses `Router.push` to navigate to the `ROUTES.ORGANISMS` page with a query filter based on the priority pathogen's category and value.
> feat: link pathogen detail pages priority tag to the organism list filtered by the prioirty (#630)

- app/components/Home/components/Section/components/SectionHero/components/Hero/hero.tsx
- app/components/Home/components/Section/components/SectionHero/sectionHero.tsx
- app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.styles.ts
- app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.tsx
- app/components/Layout/components/AppLayout/components/Section/components/SectionHero/sectionHero.tsx
- app/components/common/Section/section.tsx
Closes #636.
This pull request introduces updates to the `Hero` and `SectionHero` components to support dynamic width calculations alongside height. It also modifies the `Section` component to provide both height and width dimensions via the `useResizeObserver` hook. These changes improve layout flexibility and responsiveness.
* Added a `width` prop to the `Hero` component and updated its default value to `0`. The `width` prop is now used in the `<rect>` element instead of the hardcoded `"100%"`. (`app/components/Home/components/Section/components/SectionHero/components/Hero/hero.tsx`: [[1]](diffhunk://#diff-0858f71f2cb5c9ac753bab65d3995221e85ac3e0c419e56a0130f7f16f64c447R22-R28) [[2]](diffhunk://#diff-0858f71f2cb5c9ac753bab65d3995221e85ac3e0c419e56a0130f7f16f64c447L49-R51); …
> feat: restore hero background on home, about and roadmap pages (#636)

- app/apis/catalog/brc-analytics-catalog/common/entities.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/constants.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
- catalog/build/ts/build-catalog.ts
- catalog/build/ts/build-workflows.ts
- catalog/output/workflows.json
- catalog/py_package/catalog_build/generated_schema/schema.py
- catalog/py_package/catalog_build/iwc_manifest_to_workflows_yaml.py
- catalog/py_package/catalog_build/schema/workflows.yaml
- catalog/schema/generated/schema.ts
- catalog/schema/generated/workflows.json
- catalog/source/workflows.yml
WIP, tinkering with display still, that button isn't right -- I think instead of a button we might want just a regular link below, anyway?  This is one option.  Adds iwcID to the schema for workflows and links them up to their README page on the IWC.
closes #583
> feat: add IWC linkage from workflows

- app/views/PriorityPathogensView/priorityPathogensView.styles.ts
This fixes the new priority pathogen page not being scrollable by allowing natural content height, removing the viewport constraint.
closes #655
> fix: allow priority pathogen page scrolling

- app/views/PriorityPathogensView/priorityPathogensView.styles.ts
- package-lock.json
- package.json
Closes #668.
This pull request includes updates to the `StyledGrid` component styling and a dependency version bump for `@databiosphere/findable-ui`. The changes improve scrolling behavior and ensure compatibility with the latest UI library features.
* [`app/views/PriorityPathogensView/priorityPathogensView.styles.ts`](diffhunk://#diff-03b0be57212edecf2f1b92c6724278cdee0985e5db2e7c15fcea16037a452072L11-L19): Modified the `StyledGrid` component to override `max-height` and `overflow` properties - rather than specifying a value, provided "unset". Height override not required; refactored padding from media specificity. 
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L26-R26): Updated `@databiosphere/findable-ui` dependency from version …
> chore: update findable-ui to latest version v38.2.0 (#668)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/gtfStep.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/step.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/LaunchStep/launchStep.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/components/StepWarning/stepWarning.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/hooks/UseLaunchGalaxy/utils.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/utils/stepUtils.ts
we prev had #680 merged. id like to iterate on that, so that the behavior for missing GTFs is no worse than it was pre-stepper. we also have outstanding issue #682 but i dont want to close that w this, bc this should be revisited. i see this as an interim measure until we have ux for this properly sorted.
related to #682
> feat: warnings for failed automagical gtf files

- catalog/output/assemblies.json
- catalog/output/organisms.json
- catalog/output/outbreaks.json
- catalog/source/outbreaks.yml
talking w anton fri and he didnt love covid being highest priority. there was talk of removing the rankings entirely, but in the meantime of that i figure we can just change it from highest to critical, and have no highest priority pathogen. hopefully thats less potentially controversial.
while i was doing that i noticed a discrepancy w the measles hgphyloplace link url and fixed it.
na
> feat: update covid priority pathogen ranking

- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- site-config/brc-analytics/local/index/genomeEntityConfig.ts
Closes #716.
This pull request updates how the "is ref" property of genome entities is displayed in tables, switching from a basic cell to a chip-style cell for improved visual clarity. The changes involve updating both the component used for rendering and the supporting view model logic.
**UI Component Updates:**
* Changed the cell component for the "is ref" column in genome tables from `BasicCell` to `ChipCell`, providing a more visually distinct representation. [[1]](diffhunk://#diff-c7a9aefa9288341532869ba9987b67c489fce1e3b9e10c08643d92d54691ee11L847-R854) [[2]](diffhunk://#diff-4108318bbfd5edc450fb9ed3200ca627e0bbc349c5105d96d70235896d592037L317-R319)
* Added export for `ChipCell` in `app/components/index.ts` to make it available for use throughout the app.
**View Model Logic:**
* …
> feat: update column isref to display a chip (#716)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/constants.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/uploadMyData.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/uploadMyData.tsx
Closes #741.
This pull request refactors the `UploadMyData` component to use a styled `Alert` instead of a styled `Paper` for displaying information to the user. The changes improve the UI consistency by leveraging shared alert styles and updating the messaging.
**UI component refactor:**
* Replaced the custom `StyledPaper` component and its associated constants with a new `StyledAlert` component based on MUI's `Alert`, and removed the now-unnecessary `PAPER_PROPS` constant. [[1]](diffhunk://#diff-a9052f4e3f10ca7c56ed77514a076f2fef57710a764ee37946ac6fd73c9dbe36L1-L6) [[2]](diffhunk://#diff-21b46a45db095c91267507aa6ca47ce9ea8f489c1d0a32292cad6c8c774dd683L1-R5)
* Updated the `UploadMyData` component to use the new `StyledAlert` and MUI's `AlertTitle` for improved messaging and styling, and …
> feat: update "upload my data" ui (#741)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/viewBuilders.ts
Closes #748.
This pull request simplifies and corrects the construction of the `href` property for study accession links in the ENA Sequencing Data table. The main change ensures that the link to the NCBI BioProject is only created when a value is present, and the URL is constructed correctly.
Improvements to link handling:
* Updated the `buildStudyAccession` function in `viewBuilders.ts` to construct the `href` property using a template string only when a value exists, ensuring accurate and conditional link generation.
> fix: fix sequencing step study accession link (#748)

- package-lock.json
- package.json
Closes #770.
This pull request makes a minor update to the project's dependencies by bumping the version of the `@databiosphere/findable-ui` package from `^43.0.0` to `^44.0.0` in `package.json`.
> chore: update findable-ui to latest v44.0.0 (#770)

- site-config/brc-analytics/local/config.ts
Closes #732.
This pull request introduces a new default sorting configuration for the BRC Analytics local site config. The main change is the addition of a filter sort option that sets the default sorting method to alphabetical order.
Configuration improvements:
* Added import of `FILTER_SORT` from the shared UI library to enable sorting configuration in `config.ts`.
* Set the default `filterSort` option to sort entities alphabetically by adding `filterSort: { sortBy: FILTER_SORT.ALPHA }` to the configuration object in `makeConfig`.
> feat: configure sort by chooser (alpha or count) to filters (#732)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/hook.ts
Closes #731.
This pull request enhances the sequencing data table component by improving its layout and adding table download functionality. The main changes include updating the table's styling, introducing a toolbar, and enabling users to download table data.
**UI and Layout Improvements:**
* Updated `StyledRoundedPaper` in `table.styles.ts` to use a CSS grid layout and added a gap between elements for improved visual structure.
* Added the `TableToolbar2` component to the table UI for additional table controls and actions.
**Table Download Feature:**
* Imported the `TABLE_DOWNLOAD` constant to support table download capabilities.
* Enabled the table download feature in the `useTable` hook by adding `TABLE_DOWNLOAD` to the features array, setting a default download filename, and …
> feat: configure export as tsv to select sequencing runs table (#731)

- site-config/brc-analytics/local/config.ts
- site-config/brc-analytics/local/socialMedia.ts
Closes #842.
This pull request enhances the navigation and social media integration in the BRC Analytics site configuration. The main improvements include adding a "More" dropdown to the navigation menu, grouping social media links under a "Join Us" submenu, and standardizing social media link attributes for security and consistency.
Navigation menu improvements:
* Added a "More" dropdown to the main navigation, which contains links to "Roadmap" and a "Join Us" submenu. The "Join Us" submenu displays social media links and is conditionally visible based on screen size.
* Imported and used the new `socialMenuItems` array to populate the "Join Us" submenu, grouping social links with their respective icons. [[1]](diffhunk://#diff-d8a05cfdd5e948c0abdb37e8934842bce48a70d4dc011e7a3ebf253daf9528f …
> feat: add socials to header navigation menu for mid-sized viewports (#842)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.tsx
Closes #852.
This pull request simplifies the `CollectionSummary` component by removing the use of Material-UI Table components and related table rendering logic. The changes focus on cleaning up unused imports and removing the table display from the component, likely in preparation for a different UI approach or to reduce complexity.
**Component simplification and cleanup:**
* Removed all Material-UI Table components and related logic (such as `TableContainer`, `GridTable`, `TableHead`, `TableRow`, `TableCell`, `TableBody`, and the use of `flexRender`) from the `CollectionSummary` component, resulting in a much simpler JSX structure.
* Cleaned up imports in `collectionSummary.tsx` by removing unused table-related components and utilities.
**Styling cleanup:**
* Removed the …
> feat: update stepper ui for large number of sequences in the final step (#852)

- app/components/Home/content/sectionSubHeroGA2.mdx
Fixes #874.
This pull request makes a minor update to the `sectionSubHeroGA2.mdx` file, clarifying the description of GenomeArk by removing the word "analytics" from the introductory sentence.
> fix: remove analytics text from ga2 subhero text (#874)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.tsx
Closes #901.
This pull request introduces virtualization to the `Table` component in the ENA Sequencing Data Collection Selector, improving performance when rendering large datasets. The main changes involve integrating a virtualization hook and updating the table body to use virtualized rows.
Performance improvements (virtualization):
* Integrated the `useVirtualization` hook from `@databiosphere/findable-ui` to manage row virtualization, reducing the rendering load for large tables (`table.tsx`).
* Updated the `TableContainer` to use a `ref` from the virtualization hook, enabling efficient scrolling and rendering (`table.tsx`).
* Modified the `TableBody` component props to accept `rows` and `virtualizer` from the virtualization hook, ensuring only visible rows are rendered …
> feat: virtualize ena picker list (#901)
