- app/apis/catalog/brc-analytics-catalog/common/utils.ts
- app/components/Table/components/TableCell/components/AnalyzeGenome/analyzeGenome.tsx
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
> feat: update genome page URL to remove the "." in the genome version id (#29)

- pages/_document.tsx
> feat: implement plausible analytics (#37)

- app/theme/common/palette.ts
- app/theme/theme.ts
- app/views/HomeView/homeView.tsx
- types/theme.d.ts
Closes #53.
Home page section order updated: Your questions, answered to the end.
> fix: highlight selected page in topnav (#53)

- .prettierignore
- package.json
> chore: add format script, update prettierignore

- app/components/Support/components/ViewSupport/viewSupport.styles.ts
- site-config/brc-analytics/local/config.ts
- site-config/brc-analytics/local/floating/floating.ts
> feat: persistent help / feedback button (#81)

- .eslintignore
- app/components/Home/components/Section/components/SectionAnalytics/sectionAnalytics.tsx
- app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.tsx
- app/components/Home/content/sectionSubHero.mdx
- app/components/Layout/components/Footer/components/Branding/branding.tsx
- app/components/Roadmap/components/Section/components/SectionRoadmap/sectionRoadmap.tsx
- app/views/AboutView/aboutView.tsx
> BRC Analytics naming standardization

- app/components/Home/components/Section/components/SectionHero/components/Carousel/cards/constants.ts
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/index.tsx
- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/webinars.mdx
> feat: add banner for webinar (#116)

- app/components/Home/components/Section/components/SectionHero/components/Carousel/cards/constants.ts
> feat: comment out current homepage card about the webinar (#124)

- app/components/common/CopyText/components/ClipboardCopy/clipboardCopy.tsx
- app/components/common/CopyText/components/ClipboardCopy/constants.ts
- app/components/common/CopyText/copyText.tsx
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- package-lock.json
- package.json
> fix: copy clipboard (#121)

- app/components/Entity/components/AnalysisMethod/analysisMethod.styles.ts
- app/components/Entity/components/AnalysisMethod/analysisMethod.tsx
- app/components/Entity/components/AnalysisMethod/constants.ts
- app/components/Entity/components/AnalysisMethod/content/assembly.mdx
- app/components/Entity/components/AnalysisMethod/content/genomeComparisons.mdx
- app/components/Entity/components/AnalysisMethod/content/proteinFolding.mdx
- app/components/Entity/components/AnalysisMethod/content/regulation.mdx
- app/components/Entity/components/AnalysisMethod/content/transcriptomics.mdx
- app/components/Entity/components/AnalysisMethod/content/variantCalling.mdx
- app/components/Entity/components/AnalysisMethod/types.ts
- app/components/Entity/components/AnalysisMethod/utils.ts
- app/components/Entity/components/AnalysisMethods/analysisMethods.tsx
- app/components/Entity/components/AnalysisMethods/types.ts
- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- site-config/brc-analytics/local/entity/genome/analysisMethodMainColumn.ts
> feat: update dataset level 'choose analysis method' (#148)

- package-lock.json
- package.json
> chore: upgrade findable-ui to 15.0.0 (#167)

- package-lock.json
- package.json
- site-config/brc-analytics/local/config.ts
> feat: add version info to footer (#166)

- .prettierignore
- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- site-config/brc-analytics/local/entity/organism/assembliesTop.ts
> feat: update organism detail page (#212)

- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
> feat: add other fields to assembly details (#213)

- site-config/brc-analytics/local/entity/genome/analysisMethodsSideColumn.ts
> feat: move resources to top of assembly side column (#222)

- app/apis/catalog/brc-analytics-catalog/common/utils.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- site-config/brc-analytics/local/index/genomeEntityConfig.ts
> feat: link to organism page from assembly list and detail (#231)

- app/components/index.ts
- site-config/brc-analytics/local/socialMedia.ts
> feat: add github link to header and footer (#234)

- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
> feat: move assembly species from breadcrumbs to subtitle (#276)

- .prettierignore
- catalog/build/ts/build-catalog.ts
> style: fix prettierignoring of catalog files (#317)

- app/apis/catalog/brc-analytics-catalog/common/entities.ts
- app/components/Entity/components/AnalysisMethodsCatalog/analysisMethodsCatalog.tsx
- app/components/Entity/components/AnalysisMethodsCatalog/types.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- catalog/output/genomes.json
- catalog/output/organisms.json
- catalog/schema/generated/organisms.json
- catalog/schema/generated/schema.ts
- catalog/schema/organisms.yaml
- catalog/source/organisms.yml
> feat: allow organisms to have multiple ploidies separately matched with workflows (#334)

- app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.styles.ts
- app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.tsx
> content: explain 'free' compute at tacc (#237)

- catalog/schema/scripts/test-gen-python.sh
- catalog/schema/scripts/validate-catalog.sh
- catalog/source/organisms.yml
Closes #341
~~Not ready to merge -- will probably do some testing with this PR!~~ Ready!
> ci: fix linkml checks so that they exit with failure if the check fails for any file (#341)

- next.config.mjs
- package-lock.json
- package.json
> chore: update findable-ui to latest v22.0.0 (#391)

- catalog/build/py/package/catalog_build/build.py
Fixes https://github.com/galaxyproject/brc-analytics/issues/407
> fix: handle NCBI rate limit (#407)

- catalog/build/py/package/catalog_build/build.py
That's a bit faster (about 6 minutes in my hands).
I'll add a cron job to just update this automatically.
> chore: use requests session to reuse tcp connection (#397)

- .github/workflows/dev-deploy.yml
- .github/workflows/publish.yml
- .github/workflows/release-please.yml
Fixes https://github.com/galaxyproject/brc-analytics/issues/417
(I think)
> fix: github action syntax needs single quotes, resolves deploys (#417)

- package-lock.json
- package.json
- pages/_app.tsx
> chore: update findable-ui to latest version v24.0.0 (#429)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Top/top.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Top/utils.ts
- app/views/WorkflowInputsView/types.ts
- app/views/WorkflowInputsView/workflowInputsView.tsx
- pages/data/[entityListType]/[entityId]/[trsId]/index.tsx
- routes/constants.ts
> feat: create configure inputs title and breadcrumbs (#427)

- app/components/Entity/components/AnalysisMethod/components/Workflow/constants.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/SideColumn/sideColumn.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/SideColumn/types.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- app/views/WorkflowInputsView/workflowInputsView.tsx
> feat: create workflow configuration side column (#431)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/gtfStep.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/step.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/ReferenceAssemblyStep/referenceAssemblyStep.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/ReferenceAssemblyStep/step.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/types.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/constants.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/stepper.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/stepper.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/types.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/main.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/types.ts
- app/views/WorkflowInputsView/workflowInputsView.tsx
> feat: create workflow configuration main column with two placeholder steps (#433)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/hooks/UseUCSCFiles/useUCSCFiles.ts
> fix: add error handling to ucsc files request (#438)

- catalog/build/py/build-files-from-ncbi.py
- catalog/build/py/package/catalog_build/build.py
- catalog/build/py/package/setup.py
- catalog/output/qc-report.md
resolves #366 
i did test it a bit by removing an entry from organisms yml and running locally, before turning it back for the pr.
> feat: add check for ploidy to the assemblies qc report (#366)

- app/components/Home/components/Section/components/SectionHero/components/Carousel/content/webinar20250326.mdx
> content: update cards on main page to add webinar YouTube link (#454)

- package-lock.json
- package.json
Closes #521.
This pull request includes a version update for a dependency in the `package.json` file. The update changes the `@databiosphere/findable-ui` package from version `^32.0.1` to `^32.1.1`, likely to incorporate new features, improvements, or bug fixes.
> fix: fix back button behaviour from assemblies back to sunburst on homepage (#521)

- package-lock.json
- package.json
Closes #544.
This pull request updates the version of the `@databiosphere/findable-ui` dependency in the `package.json` file.
Dependency upgrade:
* Updated `@databiosphere/findable-ui` from version `^32.1.1` to `^33.0.0` to incorporate the latest features and fixes provided by the library.
> fix: filter labels incorrect for taxonomic level (#544)

- package-lock.json
- package.json
Closes #561.
This pull request updates the version of the `@databiosphere/findable-ui` dependency in the `package.json` file to ensure compatibility with the latest features and fixes.
Dependency updates:
* Updated `@databiosphere/findable-ui` from version `^33.0.0` to `^34.1.0` in `package.json`.
> fix: refreshing on organisms or assemblies page hangs on dev (#561)

- app/components/content/sectionAbout.mdx
- app/components/content/sectionRoadmap.mdx
`usegaxy` spotted by Ahmed, and there are a few more here as well.
> fix: typos in the about and roadmap pages (#585)

- package-lock.json
- package.json
- pages/_app.tsx
Closes #601.
This pull request updates a dependency and integrates a new provider into the application. The most important changes include upgrading the `@databiosphere/findable-ui` package and wrapping the application with the `ServicesProvider` to provide additional context or services.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L26-R26): Upgraded `@databiosphere/findable-ui` from version `^34.1.0` to `^37.1.0`, likely to incorporate new features or bug fixes.
* [`pages/_app.tsx`](diffhunk://#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029R23): Imported `ServicesProvider` from `@databiosphere/findable-ui` to enable its usage in the application.
* [`pages/_app.tsx`](diffhunk://#diff-a9827ce1be32c607c948881a89b9 …
> chore: update findable-ui to latest 37.1.0 (#601)

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.styles.ts
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.tsx
- app/components/index.ts
- app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
- app/views/PriorityPathogensView/priorityPathogensView.styles.ts
- app/views/PriorityPathogensView/priorityPathogensView.tsx
- next.config.mjs
- package-lock.json
- package.json
- site-config/brc-analytics/local/config.ts
- site-config/brc-analytics/local/index/genomeEntityConfig.ts
- site-config/brc-analytics/local/index/organismEntityConfig.ts
- site-config/brc-analytics/local/index/priorityPathogensEntityConfig.ts
Closes #635.
This pull request introduces several updates across multiple files to improve code organization, enhance UI components, and streamline configurations. The changes include refactoring imports for better modularity, updating styles and components for UI consistency, and transitioning configuration properties to a new structure.
* Updated imports for `RoundedPaper` and `FluidPaper` to use more specific paths, improving modularity and readability across multiple files. (`[[1]](diffhunk://#diff-729768a95b7f11be9d2ba63fb45e9dcf0e3e9d8569f35ccbfd76c03f37aa4a85L1-R1)`, `[[2]](diffhunk://#diff-9881be57bb1505996ccd1e7c5682ba8c6096c6876d5818a00887c52b3a03fe12L2-R8)`, `[[3]](diffhunk://#diff-ab5acd52d2bbe58facfe338cfed6cec00e93a9e328a89b7f9e0d9c6867745d8dL11-R14)`, …
> chore: update findable-ui to latest v38.1.1 (#635)

- catalog/py_package/catalog_build/iwc_manifest_to_workflows_yaml.py
> feat: add all input parameters to workflows.yml (#653)

- app/components/Entity/components/AnalysisMethod/analysisMethod.tsx
- app/components/Entity/components/AnalysisMethod/components/Workflow/types.ts
- app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
- app/components/Entity/components/AnalysisMethod/types.ts
- app/components/Entity/components/AnalysisMethodsCatalog/analysisMethodsCatalog.tsx
- pages/_app.tsx
removes 'workflow' feature flag, making the workflow stepper always on.
closes #675
> feat: remove workflow stepper feature flag

- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/ColumnFilters/columnFilters.tsx
- app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/hook.ts
Closes #730.
This pull request enhances the filtering and sorting capabilities of the ENA Sequencing Data Collection Selector table. The main improvements involve passing sorting configuration and state through the relevant components and hooks to enable more flexible filtering and sorting in the UI.
**Table filtering and sorting enhancements:**
* The `Controls` component in `ColumnFilters` now receives additional props: `filterSort`, `filterSortEnabled`, and `onFilterSortChange`, allowing it to control and display sorting options alongside filtering.
* The `useTable` hook now imports `FILTER_SORT` and includes a new `filterSort` property (set to `FILTER_SORT.ALPHA`) in its `meta` object, making sorting configuration available to table consumers. …
> feat: configure sort on select sequencing runs table columns (#730)
